# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir /usr/bin/WebAutomation2
    git clone https://github.com/bradley-dowling/WebAutomation2.git /usr/bin/WebAutomation2
    python /usr/bin/WebAutomation2/WebAutomation2_Testing.py

